services:
  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: olc-api

    restart: unless-stopped

    ports:
      - "8000:8000"

    environment:
      DOCKER_HOST: unix:///var/run/docker.sock

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    depends_on:
      postgres:
        condition: service_healthy


  postgres:
    image: postgres:16-alpine

    container_name: olc-postgres

    restart: unless-stopped

    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U postgres -d postgres"
        ]
      interval: 5s
      timeout: 5s
      retries: 10


volumes:
  postgres_data: